name: Run Automation Tests

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 10 * * *'   # runs daily at 10 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
